// This file is auto-generated by @hey-api/openapi-ts

export const AnswerCreateSchema = {
    properties: {
        respondent_ID: {
            type: 'string',
            title: 'Respondent Id'
        },
        question_ID: {
            type: 'integer',
            title: 'Question Id'
        },
        answer_given: {
            type: 'string',
            title: 'Answer Given'
        },
        confidence_given: {
            type: 'integer',
            title: 'Confidence Given'
        }
    },
    type: 'object',
    required: ['respondent_ID', 'question_ID', 'answer_given', 'confidence_given'],
    title: 'AnswerCreate'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const QuizQuestionSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        question_label: {
            type: 'string',
            title: 'Question Label'
        },
        question_text: {
            type: 'string',
            title: 'Question Text'
        },
        option_a: {
            type: 'string',
            title: 'Option A'
        },
        option_b: {
            type: 'string',
            title: 'Option B'
        },
        correct_answer: {
            type: 'string',
            title: 'Correct Answer'
        }
    },
    type: 'object',
    required: ['question_label', 'question_text', 'option_a', 'option_b', 'correct_answer'],
    title: 'QuizQuestion'
} as const;

export const RespondentCreateSchema = {
    properties: {
        respondent_ID: {
            type: 'string',
            title: 'Respondent Id'
        }
    },
    type: 'object',
    required: ['respondent_ID'],
    title: 'RespondentCreate'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;