// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { ConfidenceQuizGetQuestionsResponse, ConfidenceQuizCreateAnswerData, ConfidenceQuizCreateAnswerResponse, ConfidenceQuizCreateRespondentData, ConfidenceQuizCreateRespondentResponse } from './types.gen';

export class ConfidenceQuizService {
    /**
     * Get Questions
     * @returns QuizQuestion Successful Response
     * @throws ApiError
     */
    public static getQuestions(): CancelablePromise<ConfidenceQuizGetQuestionsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/confidence_quiz/questions'
        });
    }
    
    /**
     * Create Answer
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static createAnswer(data: ConfidenceQuizCreateAnswerData): CancelablePromise<ConfidenceQuizCreateAnswerResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/confidence_quiz/answers',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Respondent
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static createRespondent(data: ConfidenceQuizCreateRespondentData): CancelablePromise<ConfidenceQuizCreateRespondentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/confidence_quiz/respondents',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}