// This file is auto-generated by @hey-api/openapi-ts

export type AnswerCreate = {
    respondent_ID: string;
    question_ID: number;
    answer_given: string;
    confidence_given: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type QuizQuestion = {
    id?: (number | null);
    question_label: string;
    question_text: string;
    option_a: string;
    option_b: string;
    correct_answer: string;
};

export type RespondentCreate = {
    respondent_ID: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ConfidenceQuizGetQuestionsResponse = (Array<QuizQuestion>);

export type ConfidenceQuizCreateAnswerData = {
    requestBody: AnswerCreate;
};

export type ConfidenceQuizCreateAnswerResponse = (unknown);

export type ConfidenceQuizCreateRespondentData = {
    requestBody: RespondentCreate;
};

export type ConfidenceQuizCreateRespondentResponse = (unknown);