"""added respondents


Revision ID: 238b9217b7a1
Revises: b7b86091712e
Create Date: 2026-08-29 11:06:40.871245

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '238b9217b7a1'
down_revision = 'b7b86091712e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizanswer', sa.Column('confidence_given', sa.Integer(), nullable=False))
    op.add_column('respondent', sa.Column('respondent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint('quizanswer_respondent_id_fkey', 'quizanswer', type_='foreignkey')
    op.alter_column('quizanswer', 'respondent_id',
                   type_=sa.VARCHAR(),
                   postgresql_using="respondent_id::varchar")
    op.create_unique_constraint(
        "uq_respondent_respondent_id", "respondent", ["respondent_id"]
    )
    op.create_foreign_key("quizanswer_respondent_id_fkey", 'quizanswer', 'respondent', ['respondent_id'], ['respondent_id'])



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_constraint("quizanswer_respondent_id_fkey", 'quizanswer', type_='foreignkey')
    op.drop_constraint("uq_respondent_respondent_id", 'respondent', type_='unique')
    op.alter_column('quizanswer', 'respondent_id',
                   type_=sa.INTEGER(),
                   postgresql_using="respondent_id::integer")
    op.create_foreign_key('quizanswer_respondent_id_fkey', 'quizanswer', 'respondent', ['respondent_id'], ['id'])
    op.drop_column('respondent', 'respondent_id')
    op.drop_column('quizanswer', 'confidence_given')
    # ### end Alembic commands ###
