"""initial quiz models

Revision ID: afa32472f3f7
Revises: 
Create Date: 2026-08-11 22:02:07.189502

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'afa32472f3f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizquestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('optionA', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('optionB', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correct_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respondent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quizanswer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('respondent_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_given', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quizquestion.id'], ),
    sa.ForeignKeyConstraint(['respondent_id'], ['respondent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quizanswer')
    op.drop_table('respondent')
    op.drop_table('quizquestion')
    # ### end Alembic commands ###
